[package]
name = "burncloud-client"
version = "0.1.0"
edition = "2021"

[dependencies]
burncloud-common = { path = "../common" }
burncloud-core = { path = "../core" }
dioxus = { workspace = true }
dioxus-router = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }