[package]
publish.workspace = true
license.workspace = true
name = "burncloud-service-inference"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["process", "io-util", "time"] }
thiserror = { workspace = true }
serde = { workspace = true }
reqwest = { workspace = true }
burncloud-supply-contracts = { workspace = true }
burncloud-database = { workspace = true }
burncloud-supply-channel = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
burncloud-router.workspace = true
anyhow = { workspace = true }

[lints]
workspace = true
