use dioxus::prelude::*;
use dioxus_router::components::Outlet;

use crate::app::Route;
use burncloud_client_shared::components::TitleBar;

#[component]
pub fn GuestLayout() -> Element {
    rsx! {
        head {
            link { rel: "icon", href: "favicon.ico" }
            // Tailwind utilities generated by build.rs from tailwind.config.js
            style { "{include_str!(\"../assets/tailwind.css\")}" }

            // BurnCloud Design System CSS (single source of truth)
            style { "{burncloud_client_shared::styles::DESIGN_SYSTEM_CSS}" }

            // Tailwind v2 JIT Shims (static build compatibility for arbitrary values)
            // These will be gradually removed as pages migrate to --bc-* tokens
            style {
                "
                /* Animation delays */
                .animate-delay-100 {{ animation-delay: 0.1s; opacity: 0; }}
                .animate-delay-200 {{ animation-delay: 0.2s; opacity: 0; }}
                .animate-delay-300 {{ animation-delay: 0.3s; opacity: 0; }}
                .animate-delay-400 {{ animation-delay: 0.4s; opacity: 0; }}
                .animate-delay-500 {{ animation-delay: 0.5s; opacity: 0; }}
                .animate-count {{ animation: count-up 0.5s ease-out forwards; }}
                @keyframes count-up {{ from {{ opacity: 0; transform: translateY(10px); }} to {{ opacity: 1; transform: translateY(0); }} }}

                /* Magnetic hover */
                .magnetic-hover {{ transition: transform 0.3s cubic-bezier(0.16, 1, 0.3, 1); }}
                .magnetic-hover:hover {{ transform: scale(1.02) translateY(-2px); }}

                /* Tailwind gradient shims */
                .text-transparent {{ color: transparent; }}
                .bg-clip-text {{ -webkit-background-clip: text; background-clip: text; }}
                .bg-gradient-to-r {{ background-image: linear-gradient(to right, var(--tw-gradient-stops)); }}
                .bg-gradient-to-br {{ background-image: linear-gradient(to bottom right, var(--tw-gradient-stops)); }}
                .bg-gradient-to-tr {{ background-image: linear-gradient(to top right, var(--tw-gradient-stops)); }}
                .bg-gradient-to-l {{ background-image: linear-gradient(to left, var(--tw-gradient-stops)); }}
                .from-\\[\\#007AFF\\] {{ --tw-gradient-from: #007AFF; --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}
                .via-\\[\\#5856D6\\] {{ --tw-gradient-stops: var(--tw-gradient-from), #5856D6, var(--tw-gradient-to, transparent); }}
                .to-\\[\\#AF52DE\\] {{ --tw-gradient-to: #AF52DE; }}
                .to-\\[\\#5856D6\\] {{ --tw-gradient-to: #5856D6; }}
                .from-\\[\\#0071E3\\] {{ --tw-gradient-from: #0071E3; --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}
                .from-\\[\\#FF2D55\\]\\/15 {{ --tw-gradient-from: rgba(255, 45, 85, 0.15); --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}
                .via-\\[\\#AF52DE\\]\\/12 {{ --tw-gradient-stops: var(--tw-gradient-from), rgba(175, 82, 222, 0.12), var(--tw-gradient-to, transparent); }}
                .to-\\[\\#007AFF\\]\\/15 {{ --tw-gradient-to: rgba(0, 122, 255, 0.15); }}
                .from-\\[\\#30B0C7\\]\\/20 {{ --tw-gradient-from: rgba(48, 176, 199, 0.2); --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}
                .via-\\[\\#5856D6\\]\\/15 {{ --tw-gradient-stops: var(--tw-gradient-from), rgba(88, 86, 214, 0.15), var(--tw-gradient-to, transparent); }}
                .from-\\[\\#5AC8FA\\]\\/20 {{ --tw-gradient-from: rgba(90, 200, 250, 0.2); --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}
                .to-\\[\\#007AFF\\]\\/10 {{ --tw-gradient-to: rgba(0, 122, 255, 0.1); }}
                .from-\\[\\#FF9500\\]\\/10 {{ --tw-gradient-from: rgba(255, 149, 0, 0.1); --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}
                .to-\\[\\#FF2D55\\]\\/10 {{ --tw-gradient-to: rgba(255, 45, 85, 0.1); }}
                .from-\\[\\#AF52DE\\]\\/10 {{ --tw-gradient-from: rgba(175, 82, 222, 0.1); --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}
                .to-\\[\\#5856D6\\]\\/10 {{ --tw-gradient-to: rgba(88, 86, 214, 0.1); }}
                .from-\\[\\#AF52DE\\]\\/15 {{ --tw-gradient-from: rgba(175, 82, 222, 0.15); --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}
                .to-\\[\\#5856D6\\]\\/15 {{ --tw-gradient-to: rgba(88, 86, 214, 0.15); }}
                .from-\\[\\#34C759\\]\\/10 {{ --tw-gradient-from: rgba(52, 199, 89, 0.1); --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}
                .to-\\[\\#30D158\\]\\/10 {{ --tw-gradient-to: rgba(48, 209, 88, 0.1); }}
                .from-\\[\\#34C759\\]\\/15 {{ --tw-gradient-from: rgba(52, 199, 89, 0.15); --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}
                .to-\\[\\#30D158\\]\\/15 {{ --tw-gradient-to: rgba(48, 209, 88, 0.15); }}
                .from-\\[\\#007AFF\\]\\/5 {{ --tw-gradient-from: rgba(0, 122, 255, 0.05); --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}
                .to-\\[\\#5856D6\\]\\/5 {{ --tw-gradient-to: rgba(88, 86, 214, 0.05); }}
                .from-\\[\\#D97757\\] {{ --tw-gradient-from: #D97757; --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}
                .to-\\[\\#C96442\\] {{ --tw-gradient-to: #C96442; }}
                .from-\\[\\#4285F4\\] {{ --tw-gradient-from: #4285F4; --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}
                .to-\\[\\#34A853\\] {{ --tw-gradient-to: #34A853; }}
                .from-\\[\\#0077ED\\] {{ --tw-gradient-from: #0077ED; --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}
                .to-\\[\\#6E6AE8\\] {{ --tw-gradient-to: #6E6AE8; }}
                .from-white\\/90 {{ --tw-gradient-from: rgba(255, 255, 255, 0.9); --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}
                .from-white\\/80 {{ --tw-gradient-from: rgba(255, 255, 255, 0.8); --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}
                .from-white {{ --tw-gradient-from: #fff; --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}
                .to-\\[\\#F8F9FA\\] {{ --tw-gradient-to: #F8F9FA; }}
                .to-transparent {{ --tw-gradient-to: transparent; }}
                .to-white {{ --tw-gradient-to: #fff; }}
                .from-\\[\\#5856D6\\] {{ --tw-gradient-from: #5856D6; --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}

                /* Animation delays with arbitrary values */
                .\\[animation-delay\\:2s\\] {{ animation-delay: 2s; }}
                .\\[animation-delay\\:4s\\] {{ animation-delay: 4s; }}
                .\\[animation-delay\\:5s\\] {{ animation-delay: 5s; }}
                .\\[animation-delay\\:7s\\] {{ animation-delay: 7s; }}
                .\\[animation-delay\\:10s\\] {{ animation-delay: 10s; }}
                .\\[animation-delay\\:0\\.1s\\] {{ animation-delay: 0.1s; }}
                .\\[animation-delay\\:0\\.2s\\] {{ animation-delay: 0.2s; }}
                .\\[animation-delay\\:0\\.3s\\] {{ animation-delay: 0.3s; }}
                .\\[animation-delay\\:0\\.6s\\] {{ animation-delay: 0.6s; }}
                .\\[animation-delay\\:0\\.9s\\] {{ animation-delay: 0.9s; }}
                .\\[animation-delay\\:1\\.2s\\] {{ animation-delay: 1.2s; }}
                .\\[animation-delay\\:1\\.5s\\] {{ animation-delay: 1.5s; }}
                .\\[animation-delay\\:1\\.8s\\] {{ animation-delay: 1.8s; }}
                .\\[animation-delay\\:2\\.1s\\] {{ animation-delay: 2.1s; }}
                .\\[animation-delay\\:2\\.4s\\] {{ animation-delay: 2.4s; }}
                .\\[animation-duration\\:15s\\] {{ animation-duration: 15s; }}
                .\\[animation-duration\\:25s\\] {{ animation-duration: 25s; }}

                /* Blur utilities */
                .blur-\\[2px\\] {{ filter: blur(2px); }}
                .blur-\\[1px\\] {{ filter: blur(1px); }}
                .blur-\\[50px\\] {{ filter: blur(50px); }}
                .blur-\\[60px\\] {{ filter: blur(60px); }}
                .blur-\\[80px\\] {{ filter: blur(80px); }}
                .blur-\\[100px\\] {{ filter: blur(100px); }}
                .blur-\\[120px\\] {{ filter: blur(120px); }}
                .blur-3xl {{ filter: blur(64px); }}
                .backdrop-blur-md {{ backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px); }}
                .backdrop-blur-sm {{ backdrop-filter: blur(4px); -webkit-backdrop-filter: blur(4px); }}

                /* Shadow utilities */
                .shadow-lg {{ box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05); }}
                .shadow-\\[0_4px_12px_rgba\\(0\\,0\\,0\\,0\\.1\\)\\] {{ box-shadow: 0 4px 12px rgba(0,0,0,0.1); }}
                .shadow-\\[0_4px_12px_rgba\\(0\\,0\\,0\\,0\\.15\\)\\] {{ box-shadow: 0 4px 12px rgba(0,0,0,0.15); }}
                .shadow-\\[0_8px_20px_rgba\\(0\\,0\\,0\\,0\\.2\\)\\] {{ box-shadow: 0 8px 20px rgba(0,0,0,0.2); }}
                .shadow-\\[0_8px_24px_rgba\\(0\\,0\\,0\\,0\\.25\\)\\] {{ box-shadow: 0 8px 24px rgba(0,0,0,0.25); }}
                .shadow-\\[0_10px_30px_-5px_rgba\\(0\\,113\\,227\\,0\\.4\\)\\] {{ box-shadow: 0 10px 30px -5px rgba(0,113,227,0.4); }}
                .shadow-\\[0_20px_40px_-5px_rgba\\(0\\,113\\,227\\,0\\.5\\)\\] {{ box-shadow: 0 20px 40px -5px rgba(0,113,227,0.5); }}
                .shadow-\\[0_20px_50px_-12px_rgba\\(0\\,0\\,0\\,0\\.08\\)\\] {{ box-shadow: 0 20px 50px -12px rgba(0,0,0,0.08); }}
                .shadow-\\[0_30px_60px_-12px_rgba\\(0\\,0\\,0\\,0\\.15\\)\\] {{ box-shadow: 0 30px 60px -12px rgba(0,0,0,0.15); }}
                .shadow-\\[0_4px_14px_-2px_rgba\\(29\\,29\\,31\\,0\\.25\\)\\,0_12px_32px_-4px_rgba\\(29\\,29\\,31\\,0\\.15\\)\\] {{ box-shadow: 0 4px 14px -2px rgba(29,29,31,0.25), 0 12px 32px -4px rgba(29,29,31,0.15); }}
                .hover\\:shadow-\\[0_8px_24px_-4px_rgba\\(29\\,29\\,31\\,0\\.35\\)\\,0_16px_40px_-8px_rgba\\(29\\,29\\,31\\,0\\.2\\)\\]:hover {{ box-shadow: 0 8px 24px -4px rgba(29,29,31,0.35), 0 16px 40px -8px rgba(29,29,31,0.2); }}
                .shadow-\\[0_8px_32px_-4px_rgba\\(0\\,0\\,0\\,0\\.08\\)\\,0_24px_56px_-8px_rgba\\(88\\,86\\,214\\,0\\.12\\)\\] {{ box-shadow: 0 8px 32px -4px rgba(0,0,0,0.08), 0 24px 56px -8px rgba(88,86,214,0.12); }}
                .hover\\:shadow-\\[0_0_20px_rgba\\(175\\,82\\,222\\,0\\.4\\)\\]:hover {{ box-shadow: 0 0 20px rgba(175,82,222,0.4); }}
                .hover\\:shadow-\\[0_0_20px_rgba\\(52\\,199\\,89\\,0\\.4\\)\\]:hover {{ box-shadow: 0 0 20px rgba(52,199,89,0.4); }}
                .group-hover\\:shadow-\\[0_0_20px_rgba\\(175\\,82\\,222\\,0\\.4\\)\\] {{ }}
                .group:hover .group-hover\\:shadow-\\[0_0_20px_rgba\\(175\\,82\\,222\\,0\\.4\\)\\] {{ box-shadow: 0 0 20px rgba(175,82,222,0.4); }}
                .group:hover .group-hover\\:shadow-\\[0_0_20px_rgba\\(52\\,199\\,89\\,0\\.4\\)\\] {{ box-shadow: 0 0 20px rgba(52,199,89,0.4); }}
                .shadow-\\[0_8px_30px_-6px_rgba\\(88\\,86\\,214\\,0\\.12\\)\\] {{ box-shadow: 0 8px 30px -6px rgba(88,86,214,0.12); }}
                .shadow-\\[0_8px_24px_-4px_rgba\\(88\\,86\\,214\\,0\\.15\\)\\] {{ box-shadow: 0 8px 24px -4px rgba(88,86,214,0.15); }}
                .shadow-\\[0_0_8px_rgba\\(255\\,59\\,48\\,0\\.8\\)\\] {{ box-shadow: 0 0 8px rgba(255,59,48,0.8); }}
                .focus-within\\:shadow-\\[0_0_0_2px_rgba\\(88\\,86\\,214\\,0\\.3\\)\\]:focus-within {{ box-shadow: 0 0 0 2px rgba(88,86,214,0.3); }}
                .shadow-\\[0_0_0_2px_rgba\\(255\\,59\\,48\\,0\\.3\\)\\] {{ box-shadow: 0 0 0 2px rgba(255,59,48,0.3); }}
                .focus-within\\:shadow-\\[0_0_0_2px_rgba\\(255\\,59\\,48\\,0\\.4\\)\\]:focus-within {{ box-shadow: 0 0 0 2px rgba(255,59,48,0.4); }}
                .focus-within\\:shadow-\\[0_0_0_2px_rgba\\(255\\,149\\,0\\,0\\.5\\)\\]:focus-within {{ box-shadow: 0 0 0 2px rgba(255,149,0,0.5); }}
                .focus-within\\:shadow-\\[0_0_0_2px_rgba\\(52\\,199\\,89\\,0\\.5\\)\\]:focus-within {{ box-shadow: 0 0 0 2px rgba(52,199,89,0.5); }}
                .shadow-\\[0_10px_30px_-10px_rgba\\(0\\,122\\,255\\,0\\.5\\)\\] {{ box-shadow: 0 10px 30px -10px rgba(0,122,255,0.5); }}
                .hover\\:shadow-\\[0_20px_40px_-10px_rgba\\(0\\,122\\,255\\,0\\.6\\)\\]:hover {{ box-shadow: 0 20px 40px -10px rgba(0,122,255,0.6); }}

                /* Tracking */
                .tracking-\\[0\\.15em\\] {{ letter-spacing: 0.15em; }}
                .tracking-\\[0\\.2em\\] {{ letter-spacing: 0.2em; }}

                /* Rounded */
                .rounded-\\[14px\\] {{ border-radius: 14px; }}
                .rounded-\\[24px\\] {{ border-radius: 24px; }}
                .rounded-\\[28px\\] {{ border-radius: 28px; }}
                .rounded-\\[32px\\] {{ border-radius: 32px; }}

                /* Colors */
                .bg-\\[\\#F5F5F7\\] {{ background-color: #F5F5F7; }}
                .bg-\\[\\#E8E8ED\\] {{ background-color: #E8E8ED; }}
                .bg-\\[\\#D2D2D7\\] {{ background-color: #D2D2D7; }}
                .bg-\\[\\#1D1D1F\\] {{ background-color: #1D1D1F; }}
                .bg-\\[\\#2C2C2E\\] {{ background-color: #2C2C2E; }}
                .hover\\:bg-\\[\\#2C2C2E\\]:hover {{ background-color: #2C2C2E; }}
                .bg-black\\/90 {{ background-color: rgba(0, 0, 0, 0.9); }}
                .text-\\[\\#1D1D1F\\] {{ color: #1D1D1F; }}
                .text-\\[\\#6E6E73\\] {{ color: #6E6E73; }}
                .text-\\[\\#86868B\\] {{ color: #86868B; }}
                .text-\\[\\#0071E3\\] {{ color: #0071E3; }}
                .text-\\[\\#AF52DE\\] {{ color: #AF52DE; }}
                .text-\\[\\#34C759\\] {{ color: #34C759; }}
                .text-\\[\\#FF6B35\\] {{ color: #FF6B35; }}
                .bg-\\[\\#007AFF\\]\\/40 {{ background-color: rgba(0, 122, 255, 0.4); }}
                .bg-\\[\\#AF52DE\\]\\/40 {{ background-color: rgba(175, 82, 222, 0.4); }}
                .bg-\\[\\#34C759\\]\\/40 {{ background-color: rgba(52, 199, 89, 0.4); }}
                .bg-\\[\\#34C759\\] {{ background-color: #34C759; }}
                .hover\\:bg-\\[\\#D2D2D7\\]:hover {{ background-color: #D2D2D7; }}
                .hover\\:bg-\\[\\#1D1D1F\\]:hover {{ background-color: #1D1D1F; }}
                .hover\\:text-\\[\\#0071E3\\]:hover {{ color: #0071E3; }}
                .hover\\:from-\\[\\#0077ED\\]:hover {{ --tw-gradient-from: #0077ED; }}
                .hover\\:to-\\[\\#6E6AE8\\]:hover {{ --tw-gradient-to: #6E6AE8; }}

                /* Text sizes */
                .text-\\[10px\\] {{ font-size: 10px; }}
                .text-\\[11px\\] {{ font-size: 11px; }}
                .text-\\[12px\\] {{ font-size: 12px; }}
                .text-\\[13px\\] {{ font-size: 13px; }}
                .text-\\[14px\\] {{ font-size: 14px; }}
                .text-\\[15px\\] {{ font-size: 15px; }}
                .text-\\[16px\\] {{ font-size: 16px; }}
                .text-\\[17px\\] {{ font-size: 17px; }}
                .text-\\[20px\\] {{ font-size: 20px; }}
                .text-\\[22px\\] {{ font-size: 22px; }}

                /* Selection */
                .selection\\:bg-\\[\\#0071E3\\] ::selection {{ background-color: #0071E3; }}
                .selection\\:text-white ::selection {{ color: white; }}

                /* Opacity */
                .opacity-\\[0\\.015\\] {{ opacity: 0.015; }}
                .opacity-\\[0\\.03\\] {{ opacity: 0.03; }}
                .text-\\[\\#86868B\\]\\/30 {{ color: rgba(134, 134, 139, 0.3); }}
                .text-\\[\\#86868B\\]\\/40 {{ color: rgba(134, 134, 139, 0.4); }}

                /* Scale transforms */
                .hover\\:scale-\\[1\\.02\\]:hover {{ transform: scale(1.02); }}
                .hover\\:scale-\\[1\\.015\\]:hover {{ transform: scale(1.015); }}
                .hover\\:scale-\\[1\\.05\\]:hover {{ transform: scale(1.05); }}
                .hover\\:scale-105:hover {{ transform: scale(1.05); }}
                .hover\\:scale-110:hover {{ transform: scale(1.10); }}
                .active\\:scale-\\[0\\.985\\]:active {{ transform: scale(0.985); }}
                .group:hover .group-hover\\:scale-110 {{ transform: scale(1.10); }}
                .group:hover .group-hover\\:opacity-100 {{ opacity: 1; }}
                .group:hover .group-hover\\:opacity-20 {{ opacity: 0.2; }}
                .group:hover .group-hover\\:opacity-25 {{ opacity: 0.25; }}
                .group:hover .group-hover\\:opacity-80 {{ opacity: 0.8; }}

                /* Hover rotate */
                .hover\\:rotate-6:hover {{ transform: rotate(6deg); }}
                .hover\\:-rotate-6:hover {{ transform: rotate(-6deg); }}
                .group-hover\\:rotate-6 {{ }}
                .group:hover .group-hover\\:rotate-6 {{ transform: rotate(6deg); }}

                /* Translate */
                .hover\\:-translate-y-0\\.5:hover {{ transform: translateY(-0.125rem); }}
                .active\\:translate-y-0:active {{ transform: translateY(0); }}
                .disabled\\:hover\\:translate-y-0:disabled:hover {{ transform: translateY(0); }}
                .group:hover .group-hover\\:translate-x-1 {{ transform: translateX(0.25rem); }}
                .group:hover .group-hover\\:translate-x-2 {{ transform: translateX(0.5rem); }}
                .translate-y-\\[0\\.5px\\] {{ transform: translateY(0.5px); }}
                .translate-y-px {{ transform: translateY(1px); }}
                .translate-y-0\\.5 {{ transform: translateY(0.125rem); }}

                /* Group focus-within */
                .group:focus-within .group-focus-within\\:scale-110 {{ transform: scale(1.10); }}
                .group:focus-within .group-focus-within\\:text-\\[\\#007AFF\\] {{ color: #007AFF; }}

                /* Misc */
                .min-h-\\[25px\\] {{ min-height: 25px; }}
                .bg-white\\/80 {{ background-color: rgba(255, 255, 255, 0.8); }}
                .bg-white\\/90 {{ background-color: rgba(255, 255, 255, 0.9); }}
                .bg-white\\/40 {{ background-color: rgba(255, 255, 255, 0.4); }}
                .bg-white\\/20 {{ background-color: rgba(255, 255, 255, 0.2); }}
                .bg-white\\/10 {{ background-color: rgba(255, 255, 255, 0.1); }}
                .border-white\\/50 {{ border-color: rgba(255, 255, 255, 0.5); }}
                .border-white\\/30 {{ border-color: rgba(255, 255, 255, 0.3); }}
                .border-white\\/20 {{ border-color: rgba(255, 255, 255, 0.2); }}
                .drop-shadow-glow {{ filter: drop-shadow(0 0 15px rgba(88, 86, 214, 0.6)); }}
                .active\\:brightness-90:active {{ filter: brightness(0.9); }}

                /* ========== LOGIN PAGE SHIMS ========== */

                /* Login card width — responsive: full on mobile, 60vw on desktop */
                .login-card-container {{ width: 100%; }}
                @media (min-width: 768px) {{
                    .login-card-container {{ width: 80% !important; max-width: 600px; }}
                }}
                @media (min-width: 1024px) {{
                    .login-card-container {{ width: 60% !important; max-width: 900px; }}
                }}

                /* Backdrop blur */
                .backdrop-blur-2xl {{ backdrop-filter: blur(40px); -webkit-backdrop-filter: blur(40px); }}
                .backdrop-blur-xl {{ backdrop-filter: blur(24px); -webkit-backdrop-filter: blur(24px); }}

                /* Border radius with CSS variable */
                .rounded-\\[var\\(--bc-radius-xl\\)\\] {{ border-radius: var(--bc-radius-xl); }}
                .rounded-\\[var\\(--bc-radius-md\\)\\] {{ border-radius: var(--bc-radius-md); }}

                /* Login card shadow */
                .shadow-\\[0_8px_32px_rgba\\(0\\,0\\,0\\,0\\.08\\)\\] {{ box-shadow: 0 8px 32px rgba(0,0,0,0.08); }}

                /* Animate-in: fade + slide-up entrance */
                @keyframes animate-in-fade-up {{
                    0% {{ opacity: 0; transform: translateY(16px) scale(0.98); }}
                    100% {{ opacity: 1; transform: translateY(0) scale(1); }}
                }}
                .animate-in {{
                    animation: animate-in-fade-up 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards;
                }}

                /* Aurora background animation */
                @keyframes aurora {{
                    0%, 100% {{ transform: translateX(0) translateY(0) rotate(0deg) scale(1); opacity: 0.6; }}
                    25% {{ transform: translateX(50px) translateY(-30px) rotate(5deg) scale(1.1); opacity: 0.8; }}
                    50% {{ transform: translateX(-30px) translateY(50px) rotate(-5deg) scale(1.05); opacity: 0.7; }}
                    75% {{ transform: translateX(-50px) translateY(-20px) rotate(3deg) scale(0.95); opacity: 0.9; }}
                }}
                .animate-aurora {{
                    animation: aurora 20s ease-in-out infinite;
                }}

                /* Float animation */
                @keyframes float {{
                    0%, 100% {{ transform: translateY(0px); }}
                    50% {{ transform: translateY(-12px); }}
                }}
                .animate-float {{
                    animation: float 6s ease-in-out infinite;
                }}

                /* Morph animation */
                @keyframes morph {{
                    0%, 100% {{ border-radius: 60% 40% 30% 70% / 60% 30% 70% 40%; }}
                    25% {{ border-radius: 30% 60% 70% 40% / 50% 60% 30% 60%; }}
                    50% {{ border-radius: 50% 60% 30% 60% / 30% 60% 70% 40%; }}
                    75% {{ border-radius: 60% 40% 60% 30% / 70% 30% 50% 60%; }}
                }}
                .animate-morph {{
                    animation: morph 8s ease-in-out infinite;
                }}

                /* Aurora animation durations */
                .\\[animation-duration\\:30s\\] {{ animation-duration: 30s; }}
                .\\[animation-duration\\:40s\\] {{ animation-duration: 40s; }}
                .\\[animation-duration\\:20s\\] {{ animation-duration: 20s; }}

                /* Aurora animation delays */
                .\\[animation-delay\\:3s\\] {{ animation-delay: 3s; }}

                /* Login gradient colors */
                .from-\\[var\\(--bc-primary-dark\\)\\]\\/15 {{ --tw-gradient-from: color-mix(in srgb, var(--bc-primary-dark) 15%, transparent); --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}
                .via-\\[\\#AF52DE\\]\\/12 {{ --tw-gradient-stops: var(--tw-gradient-from), rgba(175, 82, 222, 0.12), var(--tw-gradient-to, transparent); }}
                .to-\\[var\\(--bc-primary\\)\\]\\/10 {{ --tw-gradient-to: color-mix(in srgb, var(--bc-primary) 10%, transparent); }}
                .from-\\[var\\(--bc-success\\)\\]\\/12 {{ --tw-gradient-from: color-mix(in srgb, var(--bc-success) 12%, transparent); --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}
                .via-\\[\\#30B0C7\\]\\/10 {{ --tw-gradient-stops: var(--tw-gradient-from), rgba(48, 176, 199, 0.1), var(--tw-gradient-to, transparent); }}
                .from-\\[var\\(--bc-warning\\)\\]\\/10 {{ --tw-gradient-from: color-mix(in srgb, var(--bc-warning) 10%, transparent); --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}
                .to-\\[var\\(--bc-danger\\)\\]\\/8 {{ --tw-gradient-to: color-mix(in srgb, var(--bc-danger) 8%, transparent); }}

                /* Login gradient text */
                .from-\\[var\\(--bc-primary-dark\\)\\] {{ --tw-gradient-from: var(--bc-primary-dark); --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, transparent); }}
                .to-\\[\\#AF52DE\\] {{ --tw-gradient-to: #AF52DE; }}
                "
            }
        }

        div { class: "h-screen w-screen overflow-hidden flex flex-col bg-base-100 text-base-content relative", "data-theme": "light",
            // Floating TitleBar (Draggable)
            div { class: "absolute top-0 left-0 w-full z-50",
                TitleBar {}
            }

            // Main Content (Centered)
            main { class: "flex-1 flex flex-col relative z-0 overflow-y-auto",
                Outlet::<Route> {}
            }
        }
    }
}
