use dioxus::prelude::*;

use crate::app::Route;
use burncloud_client_shared::components::{Sidebar, TitleBar};
use burncloud_client_shared::use_auth;
use burncloud_client_shared::DesktopMode;
use burncloud_client_shared::utils::storage::ClientState;

#[component]
pub fn Layout() -> Element {
    let auth = use_auth();
    let navigator = use_navigator();
    let is_desktop = try_use_context::<DesktopMode>().is_some();
    let top_padding = if is_desktop { "pt-8" } else { "pt-0" };

    let client_state = ClientState::load();
    let theme = client_state.theme.unwrap_or_default();
    let theme_str = theme.as_str();

    // Route guard: Check if user is authenticated
    // Only redirect on initial mount, not on every render
    use_effect(move || {
        if !auth.is_authenticated() {
            navigator.replace(Route::LoginPage {});
        }
    });

    // Prevent rendering protected content if not authenticated
    if !auth.is_authenticated() {
        return rsx! {
            div { class: "h-screen w-screen flex items-center justify-center bg-base-100",
                span { class: "loading loading-spinner loading-lg text-primary" }
            }
        };
    }

    rsx! {
        head {
            // Tailwind utilities generated by build.rs from tailwind.config.js
            style { "{include_str!(\"../assets/tailwind.css\")}" }

            // BurnCloud Design System CSS (single source of truth)
            style { "{burncloud_client_shared::styles::DESIGN_SYSTEM_CSS}" }

            // SVG defaults for icon consistency
            style {
                "svg {{ width: 1.5rem; height: 1.5rem; max-width: 100%; }}"
            }
        }

        // Main App Container
        div { class: "flex h-screen w-screen bg-base-100 text-base-content overflow-hidden select-none relative", "data-theme": "{theme_str}",

            // Floating TitleBar (Z-Index 50)
            div { class: "absolute top-0 left-0 w-full z-50 pointer-events-none",
                div { class: "pointer-events-auto",
                    TitleBar {}
                }
            }

            // Sidebar Panel
            div { class: "w-64 flex-shrink-0 flex flex-col border-r border-base-300/50 bg-base-200/50 backdrop-blur-xl {top_padding}",
                div { class: "flex-1 overflow-y-auto px-2 py-4",
                    Sidebar {}
                }
            }

            // Main Content Panel
            div { class: "flex-1 flex flex-col bg-base-100 relative min-w-0 {top_padding}",
                main { class: "flex-1 overflow-y-auto overflow-x-hidden p-6 md:p-10",
                    Outlet::<Route> {}
                }
            }
        }
    }
}
