use dioxus::prelude::*;

use crate::app::Route;
use burncloud_client_shared::components::{Sidebar, TitleBar};

#[component]
pub fn Layout() -> Element {
    rsx! {
        head {
            // Embed Tailwind v2 and DaisyUI v4 CSS locally for offline stability
            style { "{include_str!(\"../assets/tailwind.css\")}" }
            style { "{include_str!(\"../assets/daisyui.css\")}" }

            // Custom CSS & JIT Shims
            style {
                "
                :root {{
                    --font-sans: -apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
                }}
                body {{
                    font-family: var(--font-sans);
                    -webkit-font-smoothing: antialiased;
                    overflow: hidden;
                }}
                /* JIT Shims - Classes that would be generated by JIT but are missing in static build */
                .text-xxs {{ font-size: 10px; }}
                .text-xxxs {{ font-size: 8px; }}
                
                .bg-macos-red {{ background-color: #FF5F56; }}
                .border-macos-red {{ border-color: #E0443E; }}
                .text-macos-red-dark {{ color: #4E0002; }}
                
                .bg-macos-yellow {{ background-color: #FFBD2E; }}
                .border-macos-yellow {{ border-color: #E1A325; }}
                .text-macos-yellow-dark {{ color: #594119; }}
                
                .bg-macos-green {{ background-color: #27C93F; }}
                .border-macos-green {{ border-color: #1FA22E; }}
                .text-macos-green-dark {{ color: #0A5016; }}

                .shadow-glow-green {{ box-shadow: 0 0 8px rgba(34,197,94,0.6); }}

                /* Fallback for SVGs */
                svg {{
                    width: 1.5rem;
                    height: 1.5rem;
                    max-width: 100%;
                }}
                .app-drag-region {{ -webkit-app-region: drag; }}
                .app-no-drag {{ -webkit-app-region: no-drag; }}
                
                ::-webkit-scrollbar {{ width: 8px; height: 8px; }}
                ::-webkit-scrollbar-track {{ background: transparent; }}
                ::-webkit-scrollbar-thumb {{ background: rgba(0, 0, 0, 0.1); border-radius: 4px; }}
                ::-webkit-scrollbar-thumb:hover {{ background: rgba(0, 0, 0, 0.2); }}
                "
            }
        }

        // Main App Container
        div { class: "flex h-screen w-screen bg-base-100 text-base-content overflow-hidden select-none relative", "data-theme": "light",

            // Floating TitleBar (Z-Index 50)
            div { class: "absolute top-0 left-0 w-full z-50 pointer-events-none",
                div { class: "pointer-events-auto",
                    TitleBar {}
                }
            }

            // Sidebar Panel
            div { class: "w-64 flex-shrink-0 flex flex-col border-r border-base-300/50 bg-base-200/50 backdrop-blur-xl pt-8",
                div { class: "flex-1 overflow-y-auto px-2 py-4",
                    Sidebar {}
                }
            }

            // Main Content Panel
            div { class: "flex-1 flex flex-col bg-base-100 relative min-w-0 pt-8",
                main { class: "flex-1 overflow-y-auto overflow-x-hidden p-6 md:p-10",
                    Outlet::<Route> {}
                }
            }
        }
    }
}
