use dioxus::prelude::*;

use crate::app::Route;
use burncloud_client_shared::components::{Sidebar, TitleBar};
use burncloud_client_shared::use_auth;
use burncloud_client_shared::DesktopMode;

#[component]
pub fn Layout() -> Element {
    let auth = use_auth();
    let navigator = use_navigator();
    let is_desktop = try_use_context::<DesktopMode>().is_some();
    let top_padding = if is_desktop { "pt-8" } else { "pt-0" };

    // Route guard: Check if user is authenticated
    // Only redirect on initial mount, not on every render
    use_effect(move || {
        if !auth.is_authenticated() {
            navigator.replace(Route::LoginPage {});
        }
    });

    // Prevent rendering protected content if not authenticated
    if !auth.is_authenticated() {
        return rsx! {
            div { class: "h-screen w-screen flex items-center justify-center bg-base-100",
                span { class: "loading loading-spinner loading-lg text-primary" }
            }
        };
    }

    rsx! {
        head {
            // Embed Tailwind v2 and DaisyUI v4 CSS locally for offline stability
            style { "{include_str!(\"../assets/tailwind.css\")}" }
            style { "{include_str!(\"../assets/daisyui.css\")}" }

            // Custom CSS & JIT Shims
            style {
                "
                :root {{
                    --font-sans: -apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
                }}
                html, body {{
                    font-family: var(--font-sans);
                    -webkit-font-smoothing: antialiased;
                    overflow: hidden;
                    scrollbar-width: none !important; /* Firefox */
                    -ms-overflow-style: none !important; /* IE/Edge */
                }}
                /* JIT Shims - Classes that would be generated by JIT but are missing in static build */
                .text-xxs {{ font-size: 10px; }}
                .text-xxxs {{ font-size: 8px; }}
                
                .bg-macos-red {{ background-color: #FF5F56; }}
                .border-macos-red {{ border-color: #E0443E; }}
                .text-macos-red-dark {{ color: #4E0002; }}
                
                .bg-macos-yellow {{ background-color: #FFBD2E; }}
                .border-macos-yellow {{ border-color: #E1A325; }}
                .text-macos-yellow-dark {{ color: #594119; }}
                
                .bg-macos-green {{ background-color: #27C93F; }}
                .border-macos-green {{ border-color: #1FA22E; }}
                .text-macos-green-dark {{ color: #0A5016; }}

                .shadow-glow-green {{ box-shadow: 0 0 8px rgba(34,197,94,0.6); }}

                /* Fallback for SVGs */
                svg {{
                    width: 1.5rem;
                    height: 1.5rem;
                    max-width: 100%;
                }}
                .app-drag-region {{ -webkit-app-region: drag; }}
                .app-no-drag {{ -webkit-app-region: no-drag; }}
                
                /* Complete scrollbar removal - macOS style */

                /* Hide ALL scrollbars globally */
                html, body, * {{
                    scrollbar-width: none !important;
                    -ms-overflow-style: none !important;
                }}

                /* Ultra aggressive webkit scrollbar hiding */
                *::-webkit-scrollbar {{
                    display: none !important;
                    width: 0px !important;
                    height: 0px !important;
                    background: transparent !important;
                    visibility: hidden !important;
                    opacity: 0 !important;
                }}

                *::-webkit-scrollbar-track {{
                    display: none !important;
                    background: transparent !important;
                    visibility: hidden !important;
                    opacity: 0 !important;
                }}

                *::-webkit-scrollbar-thumb {{
                    display: none !important;
                    background: transparent !important;
                    visibility: hidden !important;
                    opacity: 0 !important;
                }}

                *::-webkit-scrollbar-corner {{
                    display: none !important;
                    background: transparent !important;
                    visibility: hidden !important;
                    opacity: 0 !important;
                }}

                /* Override any DaisyUI scrollbar styles */
                :root, [data-theme] {{
                    --scrollbar-width: 0px !important;
                }}

                /* Force hide scrollbars in all possible contexts */
                div, span, section, article, main, aside, nav, header, footer,
                .dropdown, .modal, .drawer, .menu, .tabs, .card, .collapse,
                .overflow-x-auto, .overflow-y-auto, .overflow-x-scroll, .overflow-y-scroll {{
                    scrollbar-width: none !important;
                    -ms-overflow-style: none !important;
                }}

                div::-webkit-scrollbar, span::-webkit-scrollbar, section::-webkit-scrollbar,
                article::-webkit-scrollbar, main::-webkit-scrollbar, aside::-webkit-scrollbar,
                nav::-webkit-scrollbar, header::-webkit-scrollbar, footer::-webkit-scrollbar,
                .dropdown::-webkit-scrollbar, .modal::-webkit-scrollbar, .drawer::-webkit-scrollbar,
                .menu::-webkit-scrollbar, .tabs::-webkit-scrollbar, .card::-webkit-scrollbar,
                .collapse::-webkit-scrollbar, .overflow-x-auto::-webkit-scrollbar,
                .overflow-y-auto::-webkit-scrollbar, .overflow-x-scroll::-webkit-scrollbar,
                .overflow-y-scroll::-webkit-scrollbar {{
                    display: none !important;
                    width: 0px !important;
                    height: 0px !important;
                }}

                /* Show scrollbars ONLY on hover for overflow containers */
                .overflow-y-auto:hover::-webkit-scrollbar,
                .overflow-x-auto:hover::-webkit-scrollbar,
                .overflow-y-scroll:hover::-webkit-scrollbar,
                .overflow-x-scroll:hover::-webkit-scrollbar {{
                    display: block !important;
                    width: 4px !important;
                    height: 4px !important;
                    visibility: visible !important;
                    opacity: 1 !important;
                }}

                .overflow-y-auto:hover::-webkit-scrollbar-thumb,
                .overflow-x-auto:hover::-webkit-scrollbar-thumb,
                .overflow-y-scroll:hover::-webkit-scrollbar-thumb,
                .overflow-x-scroll:hover::-webkit-scrollbar-thumb {{
                    display: block !important;
                    background: rgba(0, 0, 0, 0.3) !important;
                    border-radius: 2px !important;
                    visibility: visible !important;
                    opacity: 1 !important;
                }}

                .overflow-y-auto:hover::-webkit-scrollbar-thumb:hover,
                .overflow-x-auto:hover::-webkit-scrollbar-thumb:hover,
                .overflow-y-scroll:hover::-webkit-scrollbar-thumb:hover,
                .overflow-x-scroll:hover::-webkit-scrollbar-thumb:hover {{
                    background: rgba(0, 0, 0, 0.5) !important;
                }}
                "
            }
        }

        // Main App Container
        div { class: "flex h-screen w-screen bg-base-100 text-base-content overflow-hidden select-none relative", "data-theme": "light",

            // Floating TitleBar (Z-Index 50)
            div { class: "absolute top-0 left-0 w-full z-50 pointer-events-none",
                div { class: "pointer-events-auto",
                    TitleBar {}
                }
            }

            // Sidebar Panel
            div { class: "w-64 flex-shrink-0 flex flex-col border-r border-base-300/50 bg-base-200/50 backdrop-blur-xl {top_padding}",
                div { class: "flex-1 overflow-y-auto px-2 py-4",
                    Sidebar {}
                }
            }

            // Main Content Panel
            div { class: "flex-1 flex flex-col bg-base-100 relative min-w-0 {top_padding}",
                main { class: "flex-1 overflow-y-auto overflow-x-hidden p-6 md:p-10",
                    Outlet::<Route> {}
                }
            }
        }
    }
}
