[package]
name = "burncloud-client"
version = "0.1.0"
edition = "2021"
publish.workspace = true
description = "BurnCloud Dioxus client and console UI"
license.workspace = true

[features]
default = []
liveview = [
    "dep:axum",
    "dep:burncloud-database",
    "dep:dioxus-liveview",
    "dioxus/liveview",
    "dioxus/server",
]
desktop = ["dep:dioxus-desktop", "dioxus/desktop"]

[dependencies]
dioxus = { workspace = true, features = ["lib", "router"] }
dioxus-router.workspace = true

axum = { workspace = true, optional = true }
burncloud-database = { workspace = true, optional = true }
dioxus-liveview = { workspace = true, optional = true }
dioxus-desktop = { workspace = true, optional = true }

[lints]
workspace = true
