/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.rs",
    "./crates/**/src/**/*.rs",
  ],
  theme: {
    extend: {
      colors: {
        // DaisyUI-compat base-* theme colors mapped to burncloud tokens.
        // Use RGB channel form so Tailwind can generate /opacity variants
        // (bg-base-100/80, text-base-content/40, ...).
        "base-50":      "rgb(250 250 252 / <alpha-value>)",
        "base-100":     "rgb(255 255 255 / <alpha-value>)",
        "base-200":     "rgb(245 245 247 / <alpha-value>)",
        "base-300":     "rgb(229 229 234 / <alpha-value>)",
        "base-content": "rgb(29 29 31 / <alpha-value>)",
        "bc-primary": "var(--bc-primary)",
        "bc-primary-hover": "var(--bc-primary-hover)",
        "bc-primary-active": "var(--bc-primary-active)",
        "bc-primary-light": "var(--bc-primary-light)",
        "bc-primary-dark": "var(--bc-primary-dark)",
        "bc-success": "var(--bc-success)",
        "bc-success-light": "var(--bc-success-light)",
        "bc-warning": "var(--bc-warning)",
        "bc-warning-light": "var(--bc-warning-light)",
        "bc-danger": "var(--bc-danger)",
        "bc-danger-light": "var(--bc-danger-light)",
        "bc-info": "var(--bc-info)",
        "bc-info-light": "var(--bc-info-light)",
        "bc-canvas": "var(--bc-bg-canvas)",
        "bc-card": "var(--bc-bg-card-solid)",
        "bc-elevated": "var(--bc-bg-elevated)",
        "bc-hover": "var(--bc-bg-hover)",
        "bc-selected": "var(--bc-bg-selected)",
        "bc-input": "var(--bc-bg-input)",
        "bc-text": "var(--bc-text-primary)",
        "bc-text-secondary": "var(--bc-text-secondary)",
        "bc-text-tertiary": "var(--bc-text-tertiary)",
        "bc-text-disabled": "var(--bc-text-disabled)",
        "bc-on-primary": "var(--bc-text-on-accent)",
        "bc-border": "var(--bc-border)",
        "bc-border-hover": "var(--bc-border-hover)",
        "bc-focus": "var(--bc-border-focus)",
      },
      borderRadius: {
        "bc-xs": "var(--bc-radius-xs)",
        "bc-sm": "var(--bc-radius-sm)",
        "bc-md": "var(--bc-radius-md)",
        "bc-lg": "var(--bc-radius-lg)",
        "bc-xl": "var(--bc-radius-xl)",
        "bc-2xl": "var(--bc-radius-2xl)",
      },
      boxShadow: {
        "bc-xs": "var(--bc-shadow-xs)",
        "bc-sm": "var(--bc-shadow-sm)",
        "bc-md": "var(--bc-shadow-md)",
        "bc-lg": "var(--bc-shadow-lg)",
        "bc-xl": "var(--bc-shadow-xl)",
        "bc-primary": "var(--bc-shadow-primary)",
      },
      fontSize: {
        "bc-xs": "var(--bc-font-xs)",
        "bc-sm": "var(--bc-font-sm)",
        "bc-base": "var(--bc-font-base)",
        "bc-md": "var(--bc-font-md)",
        "bc-lg": "var(--bc-font-lg)",
        "bc-xl": "var(--bc-font-xl)",
        "bc-2xl": "var(--bc-font-2xl)",
        "bc-3xl": "var(--bc-font-3xl)",
      },
      spacing: {
        "bc-1": "var(--bc-space-1)",
        "bc-2": "var(--bc-space-2)",
        "bc-3": "var(--bc-space-3)",
        "bc-4": "var(--bc-space-4)",
        "bc-5": "var(--bc-space-5)",
        "bc-6": "var(--bc-space-6)",
        "bc-8": "var(--bc-space-8)",
        "bc-10": "var(--bc-space-10)",
        "bc-12": "var(--bc-space-12)",
      },
      transitionTimingFunction: {
        "bc-spring": "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      fontFamily: {
        "bc-sans": [
          "-apple-system", "BlinkMacSystemFont", "SF Pro Text", "Segoe UI",
          "Roboto", "Helvetica", "Arial", "sans-serif",
          "Apple Color Emoji", "Segoe UI Emoji",
        ],
      },
    },
  },
  plugins: [],
};
