//! Single injection point for Tailwind (layout) + BurnCloud design system (visual).
//!
//! `tailwind.css` is generated by `crates/client/build.rs` into `crates/client/src/assets/`.

use crate::styles::DESIGN_SYSTEM_CSS;
use dioxus::prelude::*;

/// Tailwind utilities built by the parent `burncloud-client` crate's `build.rs`.
pub const TAILWIND_CSS: &str = include_str!("../../../src/assets/tailwind.css");

const SVG_DEFAULTS: &str = "svg { width: 1.5rem; height: 1.5rem; max-width: 100%; }";

/// Inline `<style>` blocks for LiveView / SSR HTML shells.
pub fn liveview_style_tags() -> String {
    format!(
        "<style>{TAILWIND_CSS}</style><style>{DESIGN_SYSTEM_CSS}</style><style>{SVG_DEFAULTS}</style>"
    )
}

#[component]
pub fn AppStyles() -> Element {
    rsx! {
        style { "{TAILWIND_CSS}" }
        style { "{DESIGN_SYSTEM_CSS}" }
        style { "{SVG_DEFAULTS}" }
    }
}
