[package]
publish.workspace = true
license.workspace = true
name = "burncloud-service"
version = "0.1.0"
edition = "2021"

[dependencies]
burncloud-router.workspace = true
burncloud-service-ip.workspace = true
# burncloud-supply-model.workspace = true  # TEMP: broken dep chain
burncloud-service-monitor.workspace = true
burncloud-service-inference.workspace = true
burncloud-identity-token.workspace = true

[lints]
workspace = true
